kind: Deployment
apiVersion: apps/v1
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - resources:
          requests:
            cpu: "50m"
            memory: "256Mi"
          limits:
            cpu: "2000m"
            memory: "4096Mi"
        name: flask-app
        image: bryonsmith/flaskapp-demo:v1
        ports:
          - name: flask-port
            containerPort: 5000
---
# jenkins http port for ui
kind: Service
apiVersion: v1
metadata:
  name: flask-service
spec:
  # type: NodePort
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      name: flask-default-port
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-ingress
  annotations:
    ingressClassName: nginx
spec:
  # tls:
  # - hosts:
  #   - anthonycornell.com
  #   secretName: tls-secret
  rules:
  # - host: anthonycornell.com
  - http:
      paths:
        - path: /flask
          pathType: Prefix
          backend:
            service:
              name: flask-service
              port:
                number: 80

